name = "honhucraft"
author = "johntime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "772d8f5c1ce920ac1d2304547dc9d5806193480efdb51e5c657af44ca11e76ec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
