// Create精密构件阶段性物品定义
StartupEvents.registry('item', event => {
    
    // 阶段1：基础精密构件 (Basic Precision Component)
    event.create('basic_precision_component')
        .displayName('基础精密构件')
        .tooltip('§7Create机械的基础精密构件')
        .tooltip('§8用于制作更高级的精密构件')
        .rarity('common')
        .texture('kubejs:item/basic_precision_component')
    
    // 阶段2：进阶精密构件 (Improved Precision Component)
    event.create('improved_precision_component')
        .displayName('进阶精密构件')
        .tooltip('§7经过改良的精密构件')
        .tooltip('§8精度比基础构件更高')
        .rarity('uncommon')
        .texture('kubejs:item/improved_precision_component')
    
    // 阶段3：高级精密构件 (Advanced Precision Component)
    event.create('advanced_precision_component')
        .displayName('高级精密构件')
        .tooltip('§7高精度的机械构件')
        .tooltip('§8可用于制作复杂机械')
        .rarity('rare')
        .texture('kubejs:item/advanced_precision_component')
    
    // 阶段4：专家级精密构件 (Expert Precision Component)
    event.create('expert_precision_component')
        .displayName('专家级精密构件')
        .tooltip('§7极高精度的专业构件')
        .tooltip('§8专家级工艺的产物')
        .rarity('epic')
        .texture('kubejs:item/expert_precision_component')
    
    // 阶段5：大师级精密构件 (Master Precision Component)
    event.create('master_precision_component')
        .displayName('大师级精密构件')
        .tooltip('§7完美精度的顶级构件')
        .tooltip('§8代表了工艺的巅峰')
        .rarity('epic')
        .texture('kubejs:item/master_precision_component')
    
    // 阶段6：传奇精密构件 (Legendary Precision Component)
    event.create('legendary_precision_component')
        .displayName('§6§l传奇精密构件') // 金色粗体
        .tooltip('§6传说中的完美构件')
        .tooltip('§8超越了常规工艺的极限')
        .rarity('epic')
        .glow(true) // 添加附魔光芒
        .texture('kubejs:item/legendary_precision_component')
    
    // ============ 电路板注册 ============
    event.create('basic_circuit')
        .displayName('基础电路板')
        .tooltip('§7最基础的电路核心，适用于初级机械')
        .rarity('common')
        .texture('kubejs:item/basic_circuit')
    event.create('advanced_circuit')
        .displayName('高级电路板')
        .tooltip('§b经过升级的电路板，性能更强')
        .rarity('uncommon')
        .texture('kubejs:item/advanced_circuit')
    event.create('atomic_circuit')
        .displayName('原子电路板')
        .tooltip('§d原子级精度的电路板，适用于高端设备')
        .rarity('rare')
        .texture('kubejs:item/atomic_circuit')
    event.create('quantum_circuit')
        .displayName('量子电路板')
        .tooltip('§6量子科技的结晶，突破传统极限')
        .rarity('epic')
        .texture('kubejs:item/quantum_circuit')
    event.create('hyper_circuit')
        .displayName('超能电路板')
        .tooltip('§e超能级电路，驱动顶级机械')
        .rarity('epic')
        .texture('kubejs:item/hyper_circuit')
    event.create('cosmic_circuit')
        .displayName('宇宙电路板')
        .tooltip('§c宇宙级科技产物，终极电路板')
        .rarity('epic')
        .glow(true)
        .texture('kubejs:item/cosmic_circuit')
    
})
