#List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = "#FFFFFF"
	weight = 9000
	growthFactor = 1
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 1
	numAffixes = 1
	defaultColor = "#00ff00ff"
	weight = 400
	growthFactor = 1
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 2
	numAffixes = 2
	defaultColor = "#1E90FFff"
	weight = 300
	growthFactor = 4
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 3
	numAffixes = 3
	defaultColor = "#9900ffff"
	weight = 75
	growthFactor = 7
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 4
	numAffixes = 4
	defaultColor = "#ffd900ff"
	weight = 50
	growthFactor = 10
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 5
	numAffixes = 5
	defaultColor = "#ff0000ff"
	weight = 25
	growthFactor = 16
	effects = []
	presetAffixes = []
