[me_input_bus]
	#Defines the idle power consumption when online in an ae2 network
	# Default: 1.0
	# Range: 1.0 ~ 1.7976931348623157E308
	idlePowerDrain = 1.0

[me_advanced_input_bus]
	#Defines the idle power consumption when online in an ae2 network
	# Default: 3.0
	# Range: 1.0 ~ 1.7976931348623157E308
	idlePowerDrain = 3.0

[me_output_bus]
	#Defines the idle power consumption when online in an ae2 network
	# Default: 1.0
	# Range: 1.0 ~ 1.7976931348623157E308
	idlePowerDrain = 1.0

[me_advanced_output_bus]
	#Defines the idle power consumption when online in an ae2 network
	# Default: 3.0
	# Range: 1.0 ~ 1.7976931348623157E308
	idlePowerDrain = 3.0

[me_input_hatch]
	#Defines the idle power consumption when online in an ae2 network
	# Default: 1.0
	# Range: 1.0 ~ 1.7976931348623157E308
	idlePowerDrain = 1.0

[me_advanced_input_hatch]
	#Defines the idle power consumption when online in an ae2 network
	# Default: 3.0
	# Range: 1.0 ~ 1.7976931348623157E308
	idlePowerDrain = 3.0

[me_output_hatch]
	#Defines the idle power consumption when online in an ae2 network
	# Default: 1.0
	# Range: 1.0 ~ 1.7976931348623157E308
	idlePowerDrain = 1.0

[me_advanced_output_hatch]
	#Defines the idle power consumption when online in an ae2 network
	# Default: 3.0
	# Range: 1.0 ~ 1.7976931348623157E308
	idlePowerDrain = 3.0

["ME update interval"]
	#Defines the update interval of advanced buses/hatches inventory retrieve/insert on ae2 network, default: 10
	# Default: 10
	# Range: 1 ~ 9223372036854775807
	me_update_interval = 10
